[package]
name = "advent_of_code"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
itertools = "0.14.0"
nom = "7.1.3"
# example = "1.0.0"
